###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        restart: always
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8085:80'
        networks:
            - app-network

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        restart: always
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - app-network
    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app

networks:
  app-network:
    driver: bridge
